/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elif.vtysproje;

import com.elif.vtysproje.dal.DanismanDal;
import com.elif.vtysproje.dal.EgitimDurumuDal;
import com.elif.vtysproje.dal.IsArayanDal;
import com.elif.vtysproje.dal.IsVerenDal;
import com.elif.vtysproje.dal.MeslekDal;
import com.elif.vtysproje.dal.SaglikDurumuDal;
import com.elif.vtysproje.dal.SehirDal;
import com.elif.vtysproje.dal.UserDal;
import com.elif.vtysproje.models.Danisman;
import com.elif.vtysproje.models.EgitimDurumu;
import com.elif.vtysproje.models.IsArayan;
import com.elif.vtysproje.models.IsVeren;
import com.elif.vtysproje.models.Kullanici;
import com.elif.vtysproje.models.Mesaj;
import com.elif.vtysproje.models.Meslek;
import com.elif.vtysproje.models.SaglikDurumu;
import com.elif.vtysproje.models.Sehir;
import java.util.List;

/**
 *
 * @author ELİF
 */
public class GuncelleFrame extends javax.swing.JFrame {

    private SehirDal sehirDal = new SehirDal();
    private MeslekDal meslekDal = new MeslekDal();
    private EgitimDurumuDal egitimDurumuDal = new EgitimDurumuDal();
    private SaglikDurumuDal saglikDurumuDal = new SaglikDurumuDal();
    private DanismanDal danismanDal = new DanismanDal();
    private UserDal userDal = new UserDal();
    private IsVerenDal isVerenDal = new IsVerenDal();
    private IsArayanDal isArayanDal = new IsArayanDal();
    private Kullanici kullanici;

    /**
     * Creates new form KisiEkleFrame
     */
    public GuncelleFrame(int id) {
        initComponents();
        renderCitiesComboBox();
        renderMeslekComboBox();
        renderSaglikComboBox();
        renderEgitimComboBox();
        kullanici = userDal.getById(id);
        renderUserDetails();
    }

    private void renderUserDetails() {
        tcKimlikText.setText(kullanici.getTcNo());
        emailText.setText(kullanici.getMail());
        isimText.setText(kullanici.getAd());
        soyisimText.setText(kullanici.getSoyad());
        yasText.setText(String.valueOf(kullanici.getYas()));
        sifreText.setText(kullanici.getSifre());

        sehirlerComboBox.setSelectedItem(kullanici.getSehir().getSehirAdi());
        meslekComboBox.setSelectedItem(kullanici.getMeslek().getMeslekAdi());
        saglikDurumuComboBox.setSelectedItem(kullanici.getSaglikDurumu().getKisiselSaglikDurumAdi());
        egitimDurumuComboBox.setSelectedItem(kullanici.getEgitimDurumu().getEgitimDurumuAdi());
        cinsiyetComboBox.setSelectedItem(kullanici.getCinsiyet());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sehirlerComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        meslekComboBox = new javax.swing.JComboBox<>();
        saglikDurumuComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        soyisimText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        isimText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        egitimDurumuComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cinsiyetComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yasText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tcKimlikText = new javax.swing.JTextField();
        sifreText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kullaniciGuncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kişi Ekle");

        jLabel2.setText("Şehir");

        jLabel3.setText("Meslek");

        jLabel4.setText("Sağlık Durumu");

        jLabel5.setText("Ad");

        jLabel6.setText("Soyad");

        jLabel7.setText("Eğitim Durumu");

        cinsiyetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın", "Diğer" }));

        jLabel8.setText("Cinsiyet");

        jLabel9.setText("Yaş");

        jLabel10.setText("Email");

        jLabel11.setText("Tc Kimlik No");

        jLabel12.setText("Şifre");

        kullaniciGuncelleButton.setText("Güncelle");
        kullaniciGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciGuncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(sehirlerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(meslekComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(saglikDurumuComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(egitimDurumuComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(cinsiyetComboBox, 0, 109, Short.MAX_VALUE))
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(emailText, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tcKimlikText, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(isimText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(soyisimText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel6)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel9)
                                    .addComponent(yasText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sifreText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(kullaniciGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(77, 77, 77)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(sehirlerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meslekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saglikDurumuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(egitimDurumuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cinsiyetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcKimlikText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yasText))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soyisimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(isimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(kullaniciGuncelleButton)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciGuncelleButtonActionPerformed
        Sehir sehir = sehirDal.getByName((String) sehirlerComboBox.getSelectedItem());
        Meslek meslek = meslekDal.getByName((String) meslekComboBox.getSelectedItem());
        SaglikDurumu saglikDurumu = saglikDurumuDal.getByName((String) saglikDurumuComboBox.getSelectedItem());
        EgitimDurumu egitimDurumu = egitimDurumuDal.getByName((String) egitimDurumuComboBox.getSelectedItem());
        String cinsiyet = (String) cinsiyetComboBox.getSelectedItem();
        
        kullanici.setAd(isimText.getText());
        kullanici.setSoyad(soyisimText.getText());
        kullanici.setTcNo(tcKimlikText.getText());
        kullanici.setSifre(sifreText.getText());
        kullanici.setYas(Integer.parseInt(yasText.getText()));
        kullanici.setCinsiyet(cinsiyet);
        kullanici.setEgitimDurumu(egitimDurumu);
        kullanici.setMail(emailText.getText());
        kullanici.setMeslek(meslek);
        kullanici.setSaglikDurumu(saglikDurumu);
        kullanici.setSehir(sehir);
        
        userDal.update(kullanici);
        this.dispose();
    }//GEN-LAST:event_kullaniciGuncelleButtonActionPerformed

    private void renderCitiesComboBox() {
        List<Sehir> sehirler = sehirDal.getAll();
        sehirler.forEach(sehir -> sehirlerComboBox.addItem(sehir.getSehirAdi()));
    }

    private void renderMeslekComboBox() {
        List<Meslek> meslekler = meslekDal.getAll();
        meslekler.forEach(meslek -> meslekComboBox.addItem(meslek.getMeslekAdi()));
    }

    private void renderEgitimComboBox() {
        List<EgitimDurumu> egitimDurumlari = egitimDurumuDal.getAll();
        egitimDurumlari.forEach(egitimDurum -> egitimDurumuComboBox.addItem(egitimDurum.getEgitimDurumuAdi()));
    }

    private void renderSaglikComboBox() {
        List<SaglikDurumu> saglikDurumlari = saglikDurumuDal.getAll();
        saglikDurumlari.forEach(saglikDurumu -> saglikDurumuComboBox.addItem(saglikDurumu.getKisiselSaglikDurumAdi()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cinsiyetComboBox;
    private javax.swing.JComboBox<String> egitimDurumuComboBox;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField isimText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kullaniciGuncelleButton;
    private javax.swing.JComboBox<String> meslekComboBox;
    private javax.swing.JComboBox<String> saglikDurumuComboBox;
    private javax.swing.JComboBox<String> sehirlerComboBox;
    private javax.swing.JTextField sifreText;
    private javax.swing.JTextField soyisimText;
    private javax.swing.JTextField tcKimlikText;
    private javax.swing.JTextField yasText;
    // End of variables declaration//GEN-END:variables
}
