/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elif.vtysproje;

import com.elif.vtysproje.dal.DanismanDal;
import com.elif.vtysproje.dal.IsArayanDal;
import com.elif.vtysproje.dal.IsVerenDal;
import com.elif.vtysproje.dal.UserDal;
import com.elif.vtysproje.models.Danisman;
import com.elif.vtysproje.models.IsArayan;
import com.elif.vtysproje.models.IsVeren;
import com.elif.vtysproje.models.Kullanici;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELİF
 */
public class MainFrame extends javax.swing.JFrame {

    private UserDal userDal = new UserDal();
    private IsArayanDal isArayanDal = new IsArayanDal();
    private IsVerenDal isVerenDal = new IsVerenDal();
    private DanismanDal danismanDal = new DanismanDal();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        List<Kullanici> kullanicilar = userDal.getAll();
        renderTableData(kullanicilar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        userTypesComboBox = new javax.swing.JComboBox<>();
        silButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kullaniciIdText = new javax.swing.JTextField();
        kullaniciEkleButton1 = new javax.swing.JButton();
        guncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Soyad", "Yaş", "Mail"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        searchButton.setText("Ara");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        userTypesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tümü", "İş Arayan", "İş Veren", "Danışman" }));
        userTypesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userTypesComboBoxİtemStateChanged(evt);
            }
        });

        silButton.setText("Sil");
        silButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        kullaniciEkleButton1.setText("Kullanıcı Ekle");
        kullaniciEkleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkleButton1ActionPerformed(evt);
            }
        });

        guncelleButton.setText("Güncelle");
        guncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(userTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(373, 373, 373)
                            .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGap(523, 523, 523)
                            .addComponent(searchButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(kullaniciIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silButton)
                            .addComponent(guncelleButton))
                        .addGap(46, 46, 46))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(525, Short.MAX_VALUE)
                    .addComponent(kullaniciEkleButton1)
                    .addGap(39, 39, 39)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(silButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guncelleButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(kullaniciEkleButton1)
                    .addContainerGap(400, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renderTableData(List<Kullanici> kullanicilar) {
        String columns[] = {"Id", "Ad", "Soyad", "Yaş", "Mail"};
        Object data[][] = new Object[kullanicilar.size()][columns.length];

        for (int i = 0; i < data.length; i++) {
            data[i][0] = kullanicilar.get(i).getId();
            data[i][1] = kullanicilar.get(i).getAd();
            data[i][2] = kullanicilar.get(i).getSoyad();
            data[i][3] = kullanicilar.get(i).getYas();
            data[i][4] = kullanicilar.get(i).getMail();
        }

        DefaultTableModel model = new DefaultTableModel(data, columns);
        usersTable.setModel(model);
    }


    private void userTypesComboBoxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userTypesComboBoxİtemStateChanged

        switch (userTypesComboBox.getSelectedIndex()) {
            case 0:
                List<Kullanici> kullanicilar = userDal.getAll();
                renderTableData(kullanicilar);
                break;
            case 1:
                List<IsArayan> isArayanlar = isArayanDal.getAll();
                List<Kullanici> isArayanKullanicilar = new ArrayList<>();
                for (IsArayan isArayan : isArayanlar) {
                    isArayanKullanicilar.add(isArayan.getKullanici());
                }
                renderTableData(isArayanKullanicilar);
                break;
            case 2:
                List<IsVeren> isVerenler = isVerenDal.getAll();
                List<Kullanici> isVerenKullanicilar = new ArrayList<>();
                for (IsVeren isVeren : isVerenler) {
                    isVerenKullanicilar.add(isVeren.getKullanici());
                }
                renderTableData(isVerenKullanicilar);
                break;
            case 3:
                List<Danisman> danismanlar = danismanDal.getAll();
                List<Kullanici> danismanKullanicilar = new ArrayList<>();
                for (Danisman danisman : danismanlar) {
                    danismanKullanicilar.add(danisman.getKullanici());
                }
                renderTableData(danismanKullanicilar);
                break;
        }
    }//GEN-LAST:event_userTypesComboBoxİtemStateChanged

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButtonActionPerformed
        int id = Integer.parseInt(kullaniciIdText.getText());

        danismanDal.deleteByKullaniciId(id);
        isVerenDal.deleteByKullaniciId(id);
        isArayanDal.deleteByKullaniciId(id);

        userDal.delete(userDal.getById(id));

    }//GEN-LAST:event_silButtonActionPerformed

    private void kullaniciEkleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkleButton1ActionPerformed
        new KisiEkleFrame().setVisible(true);
    }//GEN-LAST:event_kullaniciEkleButton1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        List<Kullanici> kullanicilar = userDal.searchByName(searchText.getText());
        renderTableData(kullanicilar);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void guncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButtonActionPerformed
        new GuncelleFrame(Integer.parseInt(kullaniciIdText.getText())).setVisible(true);
    }//GEN-LAST:event_guncelleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guncelleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kullaniciEkleButton1;
    private javax.swing.JTextField kullaniciIdText;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton silButton;
    private javax.swing.JComboBox<String> userTypesComboBox;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
